### ISSUE TITLE
`dev-master` is considered as outdated by Composer

### ISSUE THREAD

**Issue by Wirone** [symfony/lts#15]
We have job in CI which checks availability of updates for packages used in our project. Currently `symfony/lts` consistently fails this job:

```
# Composer 1.7.1

$ composer outdated -D --strict
symfony/lts         dev-master ! dev-master 6de50b2 Enforces Long Term Supported versions of Symfony components
ERROR: Job failed: exit code 1
```

Any ideas?

**Comment by ronfroy** [comment]
Simply remove the useless symfony/lts package :)

**Comment by nicolas-grekas** [comment]
Yep, drop it (see readme: the dev-master version should not be used.)

**Comment by nicolas-grekas** [comment]
Ouch, wrong statement. Lts is too difficult to deal with. Drop it and use flex v1.1 + extra.symfony.require instead.

**Comment by tarlepp** [comment]
actually what I just discovered with this - it's most likely composer feature/bug.

With latest composer:
```
$ composer outdated -D
roave/security-advisories dev-master dev-master 0abc14e Prevents installation of composer packages with known security vulnerabilities: no API, simply require it
symfony/lts               dev-master dev-master 6de50b2 Enforces Long Term Supported versions of Symfony components
$
```
and after running `composer update`:
``` 
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
Generating autoload files

What about running composer global require symfony/thanks && composer thanks now?
This will spread some 💖  by sending a ★  to the GitHub repositories of your fellow package maintainers.

ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear --no-warmup [OK]
Executing script cache:warmup [OK]
Executing script assets:install --symlink --relative public [OK]
Executing script requirements-checker [OK]
Executing script security-checker security:check --end-point=http://security.sensiolabs.org/check_lock [OK]
Executing script cache:clear [OK]
Executing script assets:install public [OK]
Executing script security-checker security:check [OK]

> Companienv\Composer\ScriptHandler::run
$
``` 

And at this point `composer.lock` file looked like
```
{
            "name": "symfony/lts",
            "version": "dev-master",
            "conflict": {
....
```

Note that there isn't `source` or `dist` keys at all. And after I downgraded composer to `1.6.5` and run that `composer update` command again, then my `composer.lock` file contains following:
```
{
            "name": "symfony/lts",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/lts.git",
                "reference": "6de50b244bad631a71544b3cc3c8e206c0e5f991"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/symfony/lts/zipball/6de50b244bad631a71544b3cc3c8e206c0e5f991",
                "reference": "6de50b244bad631a71544b3cc3c8e206c0e5f991",
                "shasum": ""
            },
            "conflict": {
...
```

And after that when I run `composer outdated -D` I get:
```
$ composer outdated -D
$
```

So basically all packages are updated as expected. 

And really that `symfony/lts` package isn't the only problem within this because usually people also use `"roave/security-advisories": "dev-master"` on their `composer.json` to rule out insecure libraries/packages.

And the same thing happen with that `"roave/security-advisories": "dev-master"` dependency, with latest composer it doesn't contain version information on the `composer.lock` file and with older version it works as expected.

**Comment by mleczakm** [comment]
Already fixed in https://github.com/composer/composer/commit/3d01ef28faac1363e10fd797aa81f2a8a6cdbd95 :) dev-master of composer works as expected :)

Can be closed @Wirone :)
